%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "KannalaBrandt8"

# Camera calibration and distortion parameters (OpenCV) 
# Camera.fx: 635.142318
# Camera.fy: 659.828253
# Camera.cx: 615.493465
# Camera.cy: 342.445511

# Camera.k1: -0.238468
# Camera.k2: -0.112859
# Camera.p1: -0.000492
# Camera.p2: 0.0111333
# Camera.k3: 0.0177389

Camera1.fx: 514.85683
Camera1.fy: 512.85440
Camera1.cx: 690.01057
Camera1.cy: 328.18160

Camera1.k1: -0.01734
Camera1.k2: -0.00329
# Camera1.p1: -0.03322
# Camera1.p2: 0.00855
Camera1.k3: 0.00466
Camera1.k4: -0.00256

# Camera frames per second 
Camera.fps: 30
# Camera1.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1
# Camera1.RGB: 1

# Camera resolution
Camera.width: 1280
Camera.height: 720
# Camera1.width: 1280
# Camera1.height: 720

Camera.newWidth: 1280
Camera.newHeight: 720
# Camera1.newWidth: 1280
# Camera1.newHeight: 720

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
